### ISSUE TITLE
Save/Load Tab

### ISSUE THREAD

**Issue by Zet0rz** [Zet0rz/nZombies-Unlimited#18]
A tab for Sandbox Spawnmenu that appears allowing players in Sandbox to save their current game as an nZombies Config. It should also allow loading of other Configs, which loads those up for editing. Should have panels for naming and providing metadata, and should tie into the Save/Load system for saving the files. Should contain admin checks, both server- and clientside.

- [x] Save/Load tab
- [x] Config Metadata panels/entries
- [x] Installed/saved Config list
- [x] Config loading into edit mode (creating local copy if not already - cannot overwrite .gma or officials)
- [x] Create new config dialogue (enter filename, checks it doesn't exist - warn if so)
- [x] Config deletion

Finishing touches:
- [x] Indicate when configs are "virtual" (only exists on client until saved)

**Comment by Zet0rz** [comment]
Work in progress of the Save/Load tab. It will display the currently loaded config at the top, and then every other config below it in a scroll list.
![image](https://user-images.githubusercontent.com/13242564/52145247-c710e580-2660-11e9-9dcd-f6cad1fbf02d.png)

When a config is selected, its info is displayed in the middle section (selection will be highlighted later, the skin needs updating to support brighter colors)
![image](https://user-images.githubusercontent.com/13242564/52145332-f9224780-2660-11e9-8bdd-49069f8000b0.png)
The red text fields are disabled while you are viewing a config that isn't loaded. When you load a config, selecting it will unlock these fields and the Save button.

When no config is loaded, you can click the "Create new Config" button to make a new config temporarily on the Client, which upon clicking "Save" will be sent to the Server and created. It will also immediately load that Config (so that it appears in the top Currently Loaded area).

The "Required Addons" field contains clickable links to the addons' Steam Workshop pages. When editing a Config, this is replaced by a list of checkboxes for addon installed in your game.
![image](https://user-images.githubusercontent.com/13242564/52145457-47cfe180-2661-11e9-8c23-f8c35420d8c5.png)
When a Config is loaded, the "Create new Config" button turns into "Create new editable copy" which essentially creates a new config without unloading the current one - meaning the map isn't reloaded, and thus upon saving, this config will become a copy of the previous config.

Newly created configs are of course always Local type, and only Locals can be edited (loading any other type requires you to make that editable local copy).

When a config is loaded, the "Unload" button appears to unload it.

### Any load, unless there is no currently loaded config already, will cause a _server map reload_.

The same applies to Unload.

**Comment by Blueberryy** [comment]
Damn

**Comment by Blueberryy** [comment]
The npc's will be edited or new too?

**Comment by Blueberryy** [comment]
Code config deletion please

**Comment by Zet0rz** [comment]
With this, configs now fully save, fully load, delete, and correctly network in Sandbox. Next step is to get Extension Settings (Config Settings) saving properly, and then get loading working on nZombies. After that, the entire framework for Creative will work.

**Comment by Punkinator7** [comment]
- Save and play button Saves, but doesn't switch the game mode to Play mode.

**Comment by Zet0rz** [comment]
> * Save and play button Saves, but doesn't switch the game mode to Play mode.

Should be fixed in the latest update. It had to do with how creating a new config would show its info, but wouldn't register as selected in the config list to the left (since you didn't click there, it auto-opened), which is what the button was reading from. It now reads that or the loaded config panel.
