### ISSUE TITLE
Weapon Handling

### ISSUE THREAD

**Issue by Zet0rz** [Zet0rz/nZombies-Unlimited#21]
A system that manages weapons. It should encompass "weapon slots", at which only a given amount is accessible to the player at any time. Each slot should hold its own ammo, even if the type is otherwise shared.

Should support either custom special weapon slots (so any can be unique) with custom keybinds to access, or a certain additional set (knife, equipment 1, equipment 2, grenade, special grenade). Should also add base weapons to these slots.

- [x] Weapon slots
- [x] Weapon slot managing (weapon selection, ammo)
- [x] Weapon replacement (replace currently held slot)
- [x] Special weapon slots
- [x] Knives
- [x] Grenades
- [x] Special grenades
- [x] HUD Element
- [x] Weapons with single "mag" (rocket launchers, crossbow, etc)

**Comment by DjNathann** [comment]
> 
> 
> _**Donation Ideas**_
> 
> Just like the suggested comment in the Perks Issue,
> having an extra Configuration menu for certain ULX groups would be a great benefit for certain groups.
> (Donators, etc)
> 
> **Purpose :** This would change the guns the players spawn with, or the health they spawn with, etc.

Donation Ideas? you taking a piss mate?

**Comment by FadedFusiion** [comment]
> > _**Donation Ideas**_
> > Just like the suggested comment in the Perks Issue,
> > having an extra Configuration menu for certain ULX groups would be a great benefit for certain groups.
> > (Donators, etc)
> > **Purpose :** This would change the guns the players spawn with, or the health they spawn with, etc.
> 
> Donation Ideas? This isn't DarkRP mate.

So what you're saying is any gamemode using a Donation System is DarkRP, I mean I guess that makes sense lol?

I like DarkRP came to your mind right away, I mean I didn't even have DarkRP in mind while commenting that, but hey thats just me I guess lol.

Adding a Donation Perk system would benefit, there is no way at all you can say it wouldn't benefit at all. Better than nothing, as it currently had nothing in the previous version?
![omegalul-png-emote-1](https://user-images.githubusercontent.com/13881725/49977435-55e06c00-ff14-11e8-97ca-ee07569cfef1.png)

**Comment by DjNathann** [comment]
> 
> 
> > > _**Donation Ideas**_
> > > Just like the suggested comment in the Perks Issue,
> > > having an extra Configuration menu for certain ULX groups would be a great benefit for certain groups.
> > > (Donators, etc)
> > > **Purpose :** This would change the guns the players spawn with, or the health they spawn with, etc.
> > 
> > 
> > Donation Ideas? This isn't DarkRP mate.
> 
> So what you're saying is any gamemode using a Donation System is DarkRP, I mean I guess that makes sense lol?
> 
> I like DarkRP came to your mind right away, I mean I didn't even have DarkRP in mind while commenting that, but hey thats just me I guess lol.
> 
> Adding a Donation Perk system would benefit, there is no way at all you can say it wouldn't benefit at all. Better than nothing, as it currently had nothing in the previous version?
> ![omegalul-png-emote-1](https://user-images.githubusercontent.com/13881725/49977435-55e06c00-ff14-11e8-97ca-ee07569cfef1.png)

1. Its a not a good idea. 2. Giving players an unfair advantage isn't good. 3. If you want to monetization the gamemode then do it yourself.

**Comment by CruntDUCKY** [comment]
I would like to see compatibility with weapons that hold all their ammo with a single clip (EX half-life 2 rpg has all it's ammo in one clip), nZombies is currently incompatible with weapons that hold ammo in a single clip and I hope to see these type of weapons have compatibility with nZombies Unlimited.

**Comment by Zet0rz** [comment]
> I would like to see compatibility with weapons that hold all their ammo with a single clip

Good call, didn't think of those. I'll see what I can do when I get there!

**Comment by Zet0rz** [comment]
Weapons HUD looks like this:
![](https://i.imgur.com/DJ1G8Ju.png)

It displays all special equipment on the shadow bar that were registered as a Special Weapon slot with the third argument true (enable on HUD). This way it'll show anything that any addon might add, including shields or other nades. Each weapon can have its own HUDIcon field, or even a DrawHUDIcon function which can draw its own dynamic icon (Grenades use this to draw multiple of itself up to 4 based on its ammo).

Works with weapons with secondary ammos too:
![](https://i.imgur.com/D1BUeRB.png)

And with those weapons that don't use magazine:
![](https://i.imgur.com/CSdcTEd.png)
