### ISSUE TITLE
Multi-language support?

### ISSUE THREAD

**Issue by Blueberryy** [Zet0rz/nZombies-Unlimited#25]
In future. 
It will be good to attract people from other counties for this new gamemode.
(I recommend Zet0r to make language system like from Zombie Survival gamemode)

**Comment by nk260203** [comment]
I offer to translate from english to portuguese

**Comment by Blueberryy** [comment]
Well, Zet0r won't do that but maybe in future updates on release

**Comment by Zet0rz** [comment]
Garry's Mod already has a wide language system actually. It would be relatively simple to replace all strings with #-id and use [language.Add](http://wiki.garrysmod.com/page/language/Add) in the relevant files.

If any of you want to go through and do that, I'll gladly merge your pull requests. We should follow a pattern though, something like "#nzu.module.identifier" - for example "#nzu.revive.reviveplayer" = "Hold E to revive "
