### ISSUE TITLE
Call Of Duty crosshair?

### ISSUE THREAD

**Issue by Blueberryy** [Zet0rz/nZombies-Unlimited#31]
A feature to select crosshair design in gamemode options.

And option to disable CW and FAS hud.

**Comment by CruntDUCKY** [comment]
there are addons that can change crosshairs, but to have an official crosshair selection menu would also be fine.

**Comment by Zet0rz** [comment]
I believe most weapon packs handle their own crosshairs. Disabling these is possible by overwriting their code I suppose, but it wouldn't be a clean "works with all" solution; I'd have to overwrite each and every weapon base that exist, as well as any that might exist later or we might get "unsupported weapons" which I'd rather avoid.

I don't think I'm gonna do anything specific with the crosshair.
