### ISSUE TITLE
not being able to do literally anything when i spawn in

### ISSUE THREAD

**Issue by andretbunngirl** [Zet0rz/nZombies-Unlimited#34]
when i join in, a server, in singleplayer, i spawn with nothing, can't equip or open anything except commandbar and the pause menu thingy, and the round bar in the corner shows as "0"
is this supposed to happen?

**Comment by andretbunngirl** [comment]
oh oops, didn't read "not playable"
ignore this post please

**Comment by Blueberryy** [comment]
You can close this issue now. :p
