### ISSUE TITLE
Electricity System

### ISSUE THREAD

**Issue by Zet0rz** [Zet0rz/nZombies-Unlimited#39]
Electricity is normally a global gamestate, however since the only use Electricity has is in the context of entities, the system can be morphed to a per-entity system instead, where a global state works as the fallback. This allows individually powering entities, supporting more complicated power systems.

- [x] Global power state
- [x] Networking to clients
- [x] Power override on entities
- [x] ENT:OnElectricityOn and ENT:OnElectricityOff support
- [x] Hooks

**Comment by Punkinator7** [comment]
[ERROR] addons/nzombies-unlimited-master/gamemodes/nzombies-unlimited/gamemode/points.lua:7: attempt to compare string with number
  1. CanAfford - addons/nzombies-unlimited-master/gamemodes/nzombies-unlimited/gamemode/points.lua:7
   2. Buy - addons/nzombies-unlimited-master/gamemodes/nzombies-unlimited/gamemode/playeruse.lua:277
    3. unknown - addons/nzombies-unlimited-master/gamemodes/nzombies-unlimited/gamemode/playeruse.lua:241

This error occurred when I switched the power on
and the switch itself flicks up and slowly goes back down

**Comment by Zet0rz** [comment]
> [ERROR]

I couldn't get this error. I did fix the handle going the wrong direction (the flick you describe), which was a purely visual bug.
