### ISSUE TITLE
Zombie Spawn Script Errors

### ISSUE THREAD

**Issue by LethalDumpster** [Zet0rz/nZombies-Unlimited#41]
My eagerness prevents me from holding off before playing with this mod. As expected, some kinda error showed up. Zombie speed is the last thing I expected to break. Anyway on starting round 1, I receive this same exact error for each spawn that exists in the world. Meaning now no Zombies spawn. 

'Round starting!

[ERROR] addons/nzombies-unlimited-master/gamemodes/nzombies-unlimited/entities/entities/nzu_zombie.lua:244: attempt to get length of local 'tbl' (a nil value)
  1. SelectMovementSpeed - addons/nzombies-unlimited-master/gamemodes/nzombies-unlimited/entities/entities/nzu_zombie.lua:244
   2. dozombiespawn - addons/nzombies-unlimited-master/gamemodes/nzombies-unlimited/gamemode/round.lua:63
    3. v - addons/nzombies-unlimited-master/gamemodes/nzombies-unlimited/gamemode/round.lua:142
     4. unknown - lua/includes/modules/hook.lua:84'

**Comment by Blueberryy** [comment]
nZombies Unlimited still in development. Its will be fixed soon

**Comment by LethalDumpster** [comment]
Yeah, just making sure it wasn't specific to me. Thanks

**Comment by Zet0rz** [comment]
Fixed in aefa5d7!
