### ISSUE TITLE
HUD Management

### ISSUE THREAD

**Issue by Zet0rz** [Zet0rz/nZombies-Unlimited#5]
HUD should be modularized and able to load tables containing functions that replace individual parts of the HUD. These "Components" can then be chosen between by the Extension Settings. Each component can also have the choice "None" to completely remove that HUD component.

- [x] Registration of component types
- [x] Registration of components
- [x] Support for panel-based components
- [x] Support for HUDPaint drawing

No HUD elements will be registered by default; Each module should register their own HUD element the same way Extensions would.

**Comment by Punkinator7** [comment]
- Game over text stays after a restart of a game

**Comment by Zet0rz** [comment]
> * Game over text stays after a restart of a game

Tested this and did not find it to happen. Try again in the latest version? (There were some updates to how the game over panel is handled)
