### ISSUE TITLE
Couple of Issues I have right now

### ISSUE THREAD

**Issue by Punkinator7** [Zet0rz/nZombies-Unlimited#50]
Any and all bugs that I find or have found will be posted here, and I will test for each bug most builds.
- The zombie stop right in front of a barrier with a ton of 0s in the console too: [Zombies](https://steamcommunity.com/id/Punkinator7/screenshot/800989528968814781) [Console](https://steamcommunity.com/id/Punkinator7/screenshot/800989528968832911) edit: could be related to weld tool?
- When you have no weapons, and you pull out the grenades, it will keep it out, resulting in infinite grenades (not a problem right now, but will be once Pack-a-punch is in the mode)
- can't shoot a CW2 weapon up against a barrier
- can't throw a grenade through a barrier
- can't do damage through a barrier with melee
- CW2 and TFA weapons replace themselves when bought off a wall (different guns, even from the other's base)
- can throw grenades while down
- This error from Advanced Duplicator 2 that only occurred while playing and looking in a direction: `[Advanced Duplicator 2] lua/entities/gmod_contr_spawner/cl_init.lua:4: attempt to index field 'BaseClass' (a nil value)
  1. unknown - lua/entities/gmod_contr_spawner/cl_init.lua:4`
- color set with color tool doesn't stay in play mode
These bugs exist in the latest commit ( [a524848](https://github.com/Zet0rz/nZombies-Unlimited/commit/a524848fc99104bd220c93e442e2e58fad6143a4) )

**Comment by Zet0rz** [comment]
> * T-posing zombie:

I think I saw it myself too at some point, but not sure what caused it. Did you notice a trigger?

> * Legacy only ports over special spawns, even with other things selected in the menu

You shouldn't be able to choose which parts to port, it's just a list showing what features aren't implemented yet and won't be ported. You saying it _only_ spawns Special Spawnpoints? When I tried it, I had props, doors, normal spawns, and everything too.

> * Holding melee out when buying a weapon deletes it from existence

Good catch. I think I know how to fix that.

> * Grenades don't replenish during a round transistion

I actually thought of that just recently, probably forgot to make it when it was first made the grenade system.

I'm adding these to the to-do list. Will close when all are done (if you haven't added more by then).

**Comment by Punkinator7** [comment]
I tried only config that had a bunch of stuff (props wall buys switch, etc)
but only the special spawns spawned in

**Comment by Punkinator7** [comment]
It could be because of the props were clipping

**Comment by Punkinator7** [comment]
[nz_gm_flatgrass;Configuration of the flatass.txt](https://github.com/Zet0rz/nZombies-Unlimited/files/3145982/nz_gm_flatgrass.Configuration.of.the.flatass.txt)
This is the config I am having this issue with, sure some of the things won't spawn because of them not being implemented yet but there should be whats implemented right now

**Comment by Punkinator7** [comment]
- Power switch doesn't reset if the game ends

**Comment by Zet0rz** [comment]
> This is the config I am having this issue with,

Tested it, it turned out to be an error (which halts the loading process). It was because the config states to navlock a specific navmesh area which doesn't exist in the current navmesh. This has been fixed, but it might mean you have to verify Navlocks afterwards as you might have incorrect locks due to different Navmesh (console will report this).

The bug itself is fixed in b4f7497
