### ISSUE TITLE
Cannot use tools in Sandbox

### ISSUE THREAD

**Issue by Napalmburner** [Zet0rz/nZombies-Unlimited#51]
I cannot equip the tools in sandbox. I click on for example, wall buys, and it doesn't do anything except show me what it does in the menu.

It doesn't change the toolgun.

Any thoughts?

**Comment by Zet0rz** [comment]
This shouldn't be happening as it just uses the Sandbox tool system like all other tools do. Was this in singleplayer or multiplayer? Dedicated or listen server? And can you switch to other tools, just not nZU ones, or not any tools at all?

I know that if you switch tool tab back, it'll still highlight whichever one you had selected from before, even if you selected another one from the other tab. You have to re-click it to re-equip it. Can you confirm that it wasn't just this?

**Comment by Punkinator7** [comment]
I haven't seen anything like that when I was using the tools, The tools are fully functional of the ones that are present in the build

**Comment by Napalmburner** [comment]
@Zet0rz 
I tried both in singleplayer and multiplayer and I just cannot equip the tools.

The toolgun stays on whatever tool I was using last (defaults to rope tool)

I can spawn stuff through entities but that's it.
