### ISSUE TITLE
Collisions.

### ISSUE THREAD

**Issue by funeeh** [Zet0rz/nZombies-Unlimited#54]
Collisions- in original nZombies where zombies died their ragdolls were able to get stuck on by players, but not by other zombies. Now, with the nZombies Unlimited zombies being overall larger, when they die, players getting stuck on top of their ragdolls is much more of a problem. Not only this, but other zombies also get stuck on them, slowing down the zombie or freezing it in it's tracks.

**Comment by Zet0rz** [comment]
Non-issue. nZombies Unlimited does not create serverside ragdolls. All ragdolls created from Zombies are by default clientside and have no collision at all.

You have an addon that changes this.
