### ISSUE TITLE
Certain Weapons Behaving Oddly With Wallbuys

### ISSUE THREAD

**Issue by unit0016** [Zet0rz/nZombies-Unlimited#55]
The exact behavior is different with every weapon, but it's significant, limiting certain weapon choices. Might I suggest options to adjust where and how the models appear on wallbuys?
As an example, The TFA MMOD Shotgun - The majority of the gun does not display the price text, but otherwise behaves correctly.

**Comment by Omen267901** [comment]
Using the FAL from [this addon](https://steamcommunity.com/sharedfiles/filedetails/?id=1485039751) also caused issues. The gun functions correctly but the wallbuy shows up as a Pulse Rifle with an extremely glitchy texture.

**Comment by Zet0rz** [comment]
Screenshots?

**Comment by Omen267901** [comment]
lemme get one, will edit into this post

**Comment by Zet0rz** [comment]
Model is a non-issue. The creator of the FAL just decided to put the HL2 rifle as its world model. The same goes for the trigger bounds, as that is set based on the model itself.
