### ISSUE TITLE
Point System

### ISSUE THREAD

**Issue by Zet0rz** [Zet0rz/nZombies-Unlimited#6]
Provide a core Points system. Points should not be a separate module, as it is core to almost all other extensions and modules. Should register any damage dealt to point-giving zombies or entities (as registered by the Round system). Should support modifications and hook usage to let Extensions and modules manage stuff like double points or negative points.

- [x] Player metatable functions
- [x] Damage registration
- [x] Entity registration (metatable functions like SetGivePoints(bool)?)
- [x] Hook calling using table-formed Point object (that way hooks don't return and block remaining hooks; instead they modify the table and pass it to the next hook)
- [x] HUD Element (Show points and players)

**Comment by Zet0rz** [comment]
WIP Points HUD has been added in https://github.com/Zet0rz/nZombies-Unlimited/commit/94b4b16a6f4868ecfcc4ae8f957e8dad7ce7814e. There's a couple options to go with, but haven't decided which.
![](https://cdn.discordapp.com/attachments/192661318350798850/549697728423133194/unknown.png)
![](https://thumbs.gfycat.com/ValidAcceptableElk-size_restricted.gif)

The options can be seen in the differences of the two images. With or without names? With or without local player being larger? Harder or softer colors?

**Comment by sh4d0w59** [comment]
1. With names.  (Maybe have animated graphic behind the points be lengthened a bit to accommodate for larger names?)  Useful for seeing who's buying the next door/trap.
2. With local player being larger.  Really help differentiate who you are on the points board.
3. Softer colors.  Does softer colors include a lower opacity?

**Comment by globalcringe** [comment]
100% with sh4d0w59, but with colors potentially using player colors? Like their set shirt / model color, instead of randomly assigned like before?

**Comment by Zet0rz** [comment]
> 1\. With names.
> 2\. With local player being larger.

These two kinda conflict. If you look at the bottom image, it's gonna be hard to fit in names on the smaller ones. Perhaps if they were _slightly_ larger, it could be possible.

> 3\. Softer colors.  Does softer colors include a lower opacity?

By that I meant adding more white into it, so they aren't as vibrant but a bit more subtle, basically just lighter colors. I could lower the opacity of the shadow though, it's just 100% right now.

> 100% with sh4d0w59, but with colors potentially using player colors?

It's already player colors, uses the color from the nzu_PlayerAvatar panel to the left which updates itself whenever the player changes color! :D

>[EDIT: If it would be at all possible, a toggle between the top and bottom styles of HUD would be awesome.]

Not sure if I can build in a toggle. Well, I mean of course I can but whether it makes sense. Should it then be a clientside convar? Or should it be a different component (like how the HUD system works)? If it's a convar, it won't make sense if you ever use another component than this. If it's a component, then it's saved per-config and not up to the individual player to choose (unless they're admins and override the config)

**Comment by Zet0rz** [comment]
I think I'm satisfied with this
![](https://i.imgur.com/VXCcbg7.png)

I also got the yellow/red numbers working. They are positioned at the far right end of the HUD component at the furthest point a 32-bit integer could reach out (rather than auto-adjusting to the point text size)

**Comment by sh4d0w59** [comment]
That looks great!  Can't wait to see what you have in store for the navigation system!

**Comment by Zet0rz** [comment]
I noticed it's placed exactly on top of the place chat is, so it becomes really hard to read. Do I move chat, or do I move the points display?

**Comment by sh4d0w59** [comment]
I'd say move points.

**Comment by Zet0rz** [comment]
Move where then though? Moving too far up is kinda weird, right side doesn't work either

**Comment by sh4d0w59** [comment]
I suppose you could move the chat to the bottom middle but that would interfere with powerups...
Is the right side of the screen used for anything important besides the gun HUD?  If not then the chat could go there.
