### ISSUE TITLE
Box is missing model

### ISSUE THREAD

**Issue by Punkinator7** [Zet0rz/nZombies-Unlimited#61]
I spawned in a spawn point for the box and an Error model appeared
edit: could be referencing to the wrong path
https://steamcommunity.com/id/Punkinator7/screenshot/793110129254820371

**Comment by Blueberryy** [comment]
Mystery Box model will be on updated nZombies Unlimited content addon.
nZombies Unlimited will be updated with mystery box, annoucer and powerups when he'il finish these

**Comment by Blueberryy** [comment]
~~Check out my custom version of this gamemode (https://github.com/Blueberryy/nZombies-Unlimited)~~

**Comment by Blueberryy** [comment]
Close your issue if you read everything
