### ISSUE TITLE
Mystery Box doesn't appear to load

### ISSUE THREAD

**Issue by end360** [Zet0rz/nZombies-Unlimited#72]
I'm trying to jump the gun and get a working mystery box, I went ahead and found a model/sounds that work with the mystery box entity to use until the mystery box is fully released.

After enabling mystery box in settings none of the entities load (I tried to force spawn the mystery box spawn point and the mystery box using ulx ent) and the mystery box spawn tool doesn't show up in the menu. It looks like both of those should be functioning so I'm not sure if this is a bug or not.

Edit: The extension does actually seem to load (it's in the nzu.Extensions table and has it's functions) but the tool and entities don't load.

**Comment by Blueberryy** [comment]
Bruh, its still on development

**Comment by Blueberryy** [comment]
after zet finish 1.1 you will be able to spawn it
